In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day26-ordinal-encoding/customer.csv')

In [3]:
df.head(5)

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
df.sample(5)

    age  gender review education purchased
6    18    Male   Good    School        No
1    68  Female   Poor        UG        No
15   75    Male   Poor        UG        No
28   48    Male   Poor    School        No
11   74    Male   Good        UG       Yes

## ordinal Encoding and Label Encoding

In [24]:
df = df.iloc[:,2:]

In [6]:
df.sample(5)

     review education purchased
9      Good        UG       Yes
39     Poor        PG        No
21  Average        PG        No
5   Average    School       Yes
48     Good        UG       Yes

In [7]:
from sklearn.preprocessing import OrdinalEncoder

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [10]:
X_train

     review education
34  Average    School
27     Poor        PG
38     Good    School
13  Average    School
36     Good        UG
12     Poor    School
31     Poor    School
40     Good    School
7      Poor    School
20  Average    School
1      Poor        UG
30  Average        UG
25     Good    School
22     Poor        PG
24  Average        PG
3      Good        PG
11     Good        UG
5   Average    School
44  Average        UG
17     Poor        UG
26     Poor        PG
0   Average    School
48     Good        UG
8   Average        UG
15     Poor        UG
9      Good        UG
42     Good        PG
18     Good    School
43     Poor        PG
10     Good        UG
29  Average        UG
45     Poor        PG
47     Good        PG
6      Good    School
23     Good    School
2      Good        PG
49     Good        UG
14     Poor        PG
19     Poor        PG
32  Average        UG

In [11]:
X_test

     review education
4   Average        UG
46     Poor        PG
28     Poor    School
37  Average        PG
33     Good        PG
16     Poor        UG
35     Poor    School
41     Good        PG
39     Poor        PG
21  Average        PG

In [12]:
y_test

4      No
46     No
28     No
37    Yes
33    Yes
16    Yes
35    Yes
41    Yes
39     No
21     No
Name: purchased, dtype: object

In [13]:
y_train

34     No
27     No
38     No
13     No
36    Yes
12     No
31    Yes
40     No
7     Yes
20    Yes
1      No
30     No
25     No
22    Yes
24    Yes
3      No
11    Yes
5     Yes
44     No
17    Yes
26     No
0      No
48    Yes
8      No
15     No
9     Yes
42    Yes
18     No
43     No
10    Yes
29    Yes
45    Yes
47    Yes
6      No
23     No
2      No
49     No
14    Yes
19    Yes
32    Yes
Name: purchased, dtype: object

In [14]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [15]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [16]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [17]:
X_train

array([[1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [2., 0.],
       [0., 0.],
       [1., 0.],
       [0., 1.],
       [1., 1.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [2., 1.],
       [1., 1.],
       [0., 1.],
       [2., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [1., 1.]])

In [18]:
from sklearn.preprocessing import LabelEncoder

In [19]:
le = LabelEncoder()

In [20]:
le.fit(y_train)

LabelEncoder()

In [21]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [22]:
y_test= le.transform(y_test)
y_train = le.transform(y_train)

In [23]:
y_train

array([0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1])

## One Hot Encoding for the Nominal categorical data

In [25]:
df1 =  pd.read_csv('https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day27-one-hot-encoding/cars.csv')

In [26]:
df1.sample(5)

        brand  km_driven    fuel         owner  selling_price
6370  Hyundai      19000  Petrol   First Owner         600000
1401   Maruti      57247  Petrol   First Owner         490000
7581   Maruti     110000  Petrol   Third Owner         229999
7077     Audi      20000  Diesel   First Owner        3000000
6981  Hyundai     120000  Diesel  Second Owner         150000

In [28]:
df1.head(5)

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [31]:
df1['brand'].nunique()

32

## OneHotEncoding using Pandas

In [33]:
pd.get_dummies(df1,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

## 2. K-1 OneHotEncoding

In [35]:
pd.get_dummies(df1,columns=['fuel','owner'],dtype=int,drop_first=True) # will remove the first column that is formed from the categories

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,1,0,0,0,0,0,0
1,Skoda,120000,370000,1,0,0,0,1,0,0
2,Honda,140000,158000,0,0,1,0,0,0,1
3,Hyundai,127000,225000,1,0,0,0,0,0,0
4,Maruti,120000,130000,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,1,0,0,0,0
8124,Hyundai,119000,135000,1,0,0,1,0,0,0
8125,Maruti,120000,382000,1,0,0,0,0,0,0
8126,Tata,25000,290000,1,0,0,0,0,0,0
8127,Tata,25000,290000,1,0,0,0,0,0,0

In [43]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df1.iloc[:,0:4],df1.iloc[:,-1],test_size=0.2,random_state=2)

In [44]:
X_train

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner
...        ...        ...     ...           ...
3606      Ford      35000  Diesel   First Owner
5704    Maruti     120000  Petrol   First Owner
6637      Tata      15000  Petrol   First Owner
2575    Maruti      32500  Diesel  Second Owner
7336     Isuzu     121000  Diesel   First Owner

[6502 rows x 4 columns]

In [45]:
from sklearn.preprocessing import OneHotEncoder

In [46]:
ohe = OneHotEncoder()

In [50]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()

In [51]:
X_test_new

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], shape=(1626, 9))

In [55]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Jeep', 60000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Hyundai', 25000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Tata', 15000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 32500, 0.0, ..., 1.0, 0.0, 0.0],
       ['Isuzu', 121000, 0.0, ..., 0.0, 0.0, 0.0]],
      shape=(6502, 11), dtype=object)

## OneHotEncoding with the Top Categories

In [61]:
counts = df1['brand'].value_counts()

In [62]:
df1['brand'].nunique()
threshold = 100

In [63]:
repl = counts[counts <= threshold].index

In [67]:
pd.get_dummies(df1['brand'].replace(repl, 'uncommon'),dtype=int).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
2716,0,0,0,0,1,0,0,0,0,0,0,0,0
3518,0,0,0,0,0,0,0,0,0,0,0,0,1
3064,0,0,0,0,0,0,1,0,0,0,0,0,0
6951,0,0,0,0,0,0,0,0,1,0,0,0,0
4576,0,0,0,1,0,0,0,0,0,0,0,0,0